# Generated by Django 5.2.12 on 2026-04-03 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('unidad_de_medida', models.CharField(choices=[('kg', 'Kilogramos'), ('gr', 'Gramos'), ('lt', 'Litros'), ('ml', 'Mililitros'), ('unidades', 'Unidades')], max_length=10)),
                ('precio_costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('Entrante', 'Entrante'), ('Principal', 'Principal'), ('Postre', 'Postre'), ('Bebida', 'Bebida')], default='Principal', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_necesaria', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ingrediente', models.ForeignKey(db_column='Ingredientes_id', on_delete=django.db.models.deletion.RESTRICT, to='matriz.ingrediente')),
                ('plato', models.ForeignKey(db_column='Platos_ID', on_delete=django.db.models.deletion.CASCADE, to='matriz.plato')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_vendida', models.IntegerField()),
                ('fecha_venta', models.DateField(auto_now_add=True)),
                ('plato', models.ForeignKey(db_column='plato_id', on_delete=django.db.models.deletion.CASCADE, to='matriz.plato')),
            ],
        ),
    ]
