# Generated by Django 5.2.12 on 2026-04-04 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='precio_costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='unidad_de_medida',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='cantidad_necesaria',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receta',
            name='ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriz.ingrediente'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='plato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriz.plato'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='plato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriz.plato'),
        ),
    ]
