# Generated by Django 5.2.12 on 2026-04-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriz', '0002_alter_ingrediente_precio_costo_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='unidad_de_medida',
            field=models.CharField(choices=[('GR', 'Gramos'), ('KG', 'Kilogramos'), ('ML', 'Mililitros'), ('LT', 'Litros'), ('UN', 'Unidad/Pieza')], default='GR', max_length=2),
        ),
    ]
