# Generated by Django 5.2.12 on 2026-04-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriz', '0003_alter_ingrediente_unidad_de_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='unidad_de_medida',
            field=models.CharField(choices=[('GR', 'Gramos'), ('KG', 'Kilogramos'), ('ML', 'Mililitros'), ('LT', 'Litros'), ('UN', 'Unidad/Pieza')], default='GR', max_length=100),
        ),
    ]
